[metadata]
name = model-duplication
version = 0.4.1
author = "Stefano Camborda La Cruz, Jan-Niklas Weder, Nadine Töpfer
author_email = author@example.com
description = A small example package
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/Toepfer-Lab/model_duplication
project_urls =
    Bug Tracker = https://github.com/Toepfer-Lab/model_duplication/issues
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.7
install_requires =
    prettytable
    rich
    cobra >= 0.25.0
    typing_extensions
    xmlschema
    ipycytoscape
    networkx
    IPython
    ipywidgets>=7.6.0
    graphviz
    igraph
    requests
    tqdm

[options.packages.find]
where = src

[options.package_data]
model_duplication.resources = *.xsd
